# Generated by Django 3.1.5 on 2021-01-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210122_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='euvi',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='name_pet',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='euvi',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='euvi',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
